# Generated by Django 2.0.2 on 2019-03-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='last_name',
        ),
    ]
