# Generated by Django 2.0.2 on 2020-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='kutiva/static/images/default-profile-2020.webp', upload_to=''),
        ),
    ]
