# Generated by Django 2.0.2 on 2020-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200330_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='kutiva/static/images/default-profile-2020.jpg', upload_to=''),
        ),
    ]
