# Generated by Django 2.0.2 on 2019-04-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_date',
            new_name='registed_at',
        ),
    ]
