# Generated by Django 2.0.2 on 2019-04-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='last_date',
            new_name='last_day',
        ),
    ]
