# Generated by Django 2.0.2 on 2019-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190428_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registed_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
