# Generated by Django 2.0.2 on 2019-04-28 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190428_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='start_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
