# Generated by Django 2.0.2 on 2019-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190413_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='course',
        ),
        migrations.AddField(
            model_name='enrolled',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='cms.Course'),
        ),
    ]
