# Generated by Django 2.0.2 on 2019-04-14 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0005_auto_20190413_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='user',
        ),
        migrations.AddField(
            model_name='enrolled',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
