# Generated by Django 2.0.2 on 2020-03-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(),
        ),
    ]
