# Generated by Django 2.0.2 on 2020-03-27 22:08

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20200324_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
