# Generated by Django 2.0.2 on 2020-03-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200328_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
