# Generated by Django 2.0.2 on 2020-03-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20200328_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
