# Generated by Django 2.0.2 on 2020-04-03 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20200328_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.date(2020, 4, 3))),
                ('month', models.IntegerField(default=1)),
                ('expired_date', models.DateTimeField(blank=True, default=datetime.date(2020, 5, 3))),
            ],
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
    ]
