# Generated by Django 2.0.2 on 2020-04-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20200403_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expired_date',
        ),
    ]
