# Generated by Django 2.0.2 on 2020-04-03 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_remove_subscription_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 5, 3)),
        ),
    ]
