# Generated by Django 2.0.2 on 2020-04-03 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_subscription_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 3)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_date',
            field=models.DateTimeField(default=datetime.date(2020, 5, 3)),
        ),
    ]
