# Generated by Django 2.0.2 on 2020-04-03 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20200403_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
