# Generated by Django 2.0.2 on 2020-04-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20200403_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
