# Generated by Django 2.0.2 on 2020-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20200403_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='cms.SubscriptionType'),
        ),
    ]
