# Generated by Django 2.0.2 on 2020-04-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20200406_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_date',
            field=models.DateField(default=datetime.date(2020, 5, 15)),
        ),
    ]
