# Generated by Django 2.0.2 on 2019-03-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190311_2210'),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='author',
        ),
        migrations.AddField(
            model_name='talk',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Speaker'),
            preserve_default=False,
        ),
    ]
