# Generated by Django 2.0.2 on 2019-03-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20190311_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='user',
            new_name='author',
        ),
    ]
